### ISSUE TITLE
Not working; no games listed

### ISSUE THREAD

**Issue by Kuki77** [Ertego/gog-galaxy-itch.io#33]
Hi,
yesterday fresh installation done. But no games listed. 
An error reoccurs many times in the log file.

Log:
`8:06:27,410 - root - DEBUG - Using proactor: IocpProactor
2020-12-12 18:06:27,412 - root - INFO - Using local address: 127.0.0.1:51477
2020-12-12 18:06:27,413 - root - INFO - Creating plugin for platform itch, version 0.1
2020-12-12 18:06:27,477 - root - DEBUG - Received 66 bytes of data
2020-12-12 18:06:27,478 - root - INFO - Handling request: id=0, method=get_capabilities, params={}
2020-12-12 18:06:27,478 - root - DEBUG - Sending data: {"jsonrpc": "2.0", "id": "0", "result": {"platform_name": "itch", "features": ["ImportGameTime", "LaunchGame", "UninstallGame", "ImportOwnedGames", "ImportInstalledGames"], "token": "e37760fe-0568-4abd-83b3-5d096c5c5489"}}
2020-12-12 18:06:27,479 - root - DEBUG - Task manager jsonrpc server: creating task 0 (drain)
2020-12-12 18:06:27,479 - root - DEBUG - Task manager jsonrpc server: finished task 0 (drain)
2020-12-12 18:06:27,590 - root - DEBUG - Received 75 bytes of data
2020-12-12 18:06:27,590 - root - INFO - Handling request: id=1, method=initialize_cache, params={'data': '****'}
2020-12-12 18:06:27,591 - root - DEBUG - Task manager plugin internal: creating task 0 (tick)
2020-12-12 18:06:27,591 - root - DEBUG - Sending data: {"jsonrpc": "2.0", "id": "1", "result": null}
2020-12-12 18:06:27,591 - root - DEBUG - Task manager jsonrpc server: creating task 1 (drain)
2020-12-12 18:06:27,591 - root - DEBUG - Task manager plugin external: creating task 0 (cfng)
2020-12-12 18:06:27,591 - root - DEBUG - Task manager jsonrpc server: finished task 1 (drain)
2020-12-12 18:06:27,592 - root - DEBUG - Checking for changes in the itch butler.db
2020-12-12 18:06:27,592 - root - DEBUG - Opening connection to itch butler.db
2020-12-12 18:06:27,592 - root - ERROR - Task manager plugin external: exception raised in task 0 (cfng)
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\GOG.com\Galaxy\plugins\installed\itch\galaxy\task_manager.py", line 17, in task_wrapper
    result = await coro
  File "C:\Users\USER\AppData\Local\GOG.com\Galaxy\plugins\installed\itch\itch.py", line 83, in check_for_new_games
    games_after = await self.get_games()
  File "C:\Users\USER\AppData\Local\GOG.com\Galaxy\plugins\installed\itch\itch.py", line 32, in get_games
    self.itch_db = sqlite3.connect(ITCH_DB_PATH)
sqlite3.OperationalError: unable to open database file
2020-12-12 18:06:27,691 - root - DEBUG - Received 54 bytes of data
2020-12-12 18:06:27,692 - root - INFO - Handling request: id=2, method=ping, params={}
2020-12-12 18:06:27,692 - root - DEBUG - Sending data: {"jsonrpc": "2.0", "id": "2", "result": null}
2020-12-12 18:06:27,692 - root - DEBUG - Task manager jsonrpc server: creating task 2 (drain)
2020-12-12 18:06:27,692 - root - DEBUG - Task manager jsonrpc server: finished task 2 (drain)
2020-12-12 18:06:27,913 - root - DEBUG - Received 149 bytes of data
2020-12-12 18:06:27,914 - root - INFO - Handling request: id=3, method=init_authentication, params={'stored_credentials': '****'}
2020-12-12 18:06:27,914 - root - DEBUG - Task manager jsonrpc server: creating task 3 (init_authentication)
2020-12-12 18:06:27,914 - root - DEBUG - Task manager plugin external: creating task 1 (init_authentication)
2020-12-12 18:06:28,593 - root - DEBUG - Task manager plugin external: creating task 2 (cfng)
2020-12-12 18:06:28,593 - root - DEBUG - Checking for changes in the itch butler.db
2020-12-12 18:06:28,593 - root - DEBUG - Opening connection to itch butler.db
2020-12-12 18:06:28,594 - root - ERROR - Task manager plugin external: exception raised in task 2 (cfng)
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\GOG.com\Galaxy\plugins\installed\itch\galaxy\task_manager.py", line 17, in task_wrapper
    result = await coro
  File "C:\Users\USER\AppData\Local\GOG.com\Galaxy\plugins\installed\itch\itch.py", line 83, in check_for_new_games
    games_after = await self.get_games()
  File "C:\Users\USER\AppData\Local\GOG.com\Galaxy\plugins\installed\itch\itch.py", line 32, in get_games
    self.itch_db = sqlite3.connect(ITCH_DB_PATH)
sqlite3.OperationalError: unable to open database file
2020-12-12 18:06:28,632 - root - DEBUG - Task manager plugin external: finished task 1 (init_authentication)
2020-12-12 18:06:28,633 - root - DEBUG - Sending data: {"jsonrpc": "2.0", "id": "3", "result": {"user_id": 000000000, "user_name": "xxxxxxxxxxx"}}
2020-12-12 18:06:28,633 - root - DEBUG - Task manager jsonrpc server: creating task 4 (drain)
2020-12-12 18:06:28,633 - root - DEBUG - Task manager jsonrpc server: finished task 3 (init_authentication)`
....

and so on.

**Comment by jakopo87** [comment]
Do you have the itch client installed in its default location?

**Comment by Kuki77** [comment]
Ciao Jakopo,

during the installation of the itch client I used the suggested / prefilled installation path.
In my case it was c:\Users\<Users>\AppData\Local\itch\

So yes, it's there. Or should it be somewhere else?

Saluti
Kuki77

**Comment by jakopo87** [comment]
Does the file `C:\Users\<user>\AppData\Roaming\itch\db\butler.db` exists?

**Comment by Kuki77** [comment]
Yes, it in the named location. 

I also disconnected GogGalaxy and itch and reconnected it again now.... other error messages in the log.
In the plugin-itch log I can see, that it's finding the games ... but in Galaxy there are no listed.

`2020-12-13 13:24:36,136 - root - DEBUG - Task manager plugin external: creating task 50 (cfng)
2020-12-13 13:24:36,136 - root - DEBUG - Checking for changes in the itch butler.db
2020-12-13 13:24:36,137 - root - DEBUG - Opening connection to itch butler.db
2020-12-13 13:24:36,142 - root - DEBUG - Closing connection to itch butler.db
2020-12-13 13:24:36,142 - root - DEBUG - Starting building games...
2020-12-13 13:24:36,142 - root - DEBUG - Building game 91 (Alcarys Complex)
2020-12-13 13:24:36,142 - root - DEBUG - Game 91 (Alcarys Complex) seems to be only cached, skipping...
2020-12-13 13:24:36,143 - root - DEBUG - Building game 120345 (Fumiko!)
2020-12-13 13:24:36,143 - root - DEBUG - Game 120345 (Fumiko!) seems to be only cached, skipping...
2020-12-13 13:24:36,143 - root - DEBUG - Building game 447744 (Ryza Roads)
2020-12-13 13:24:36,143 - root - DEBUG - Game 447744 (Ryza Roads) seems to be only cached, skipping...
2020-12-13 13:24:36,143 - root - DEBUG - Building game 451566 (ONYX CLAD)
2020-12-13 13:24:36,144 - root - DEBUG - Game 451566 (ONYX CLAD) seems to be only cached, skipping...
2020-12-13 13:24:36,144 - root - DEBUG - Building game 567765 (Plokoth)
2020-12-13 13:24:36,144 - root - DEBUG - Game 567765 (Plokoth) seems to be only cached, skipping...
2020-12-13 13:24:36,144 - root - DEBUG - Building game 630526 (The Imagined Leviathan)
2020-12-13 13:24:36,144 - root - DEBUG - Game 630526 (The Imagined Leviathan) seems to be only cached, skipping...
2020-12-13 13:24:36,144 - root - DEBUG - Building game 704617 (Arabel)
2020-12-13 13:24:36,145 - root - DEBUG - Game 704617 (Arabel) seems to be only cached, skipping...
2020-12-13 13:24:36,145 - root - DEBUG - Finished building games
2020-12-13 13:24:36,145 - root - DEBUG - Finished checking for changes in the itch butler.db
2020-12-13 13:24:36,145 - root - DEBUG - Task manager plugin external: finished task 50 (cfng)
`

BTW 
How to insert code here the proper way?!

**Comment by jakopo87** [comment]
Sometime it takes a while to show games (I have this problem with the Indiegala integrations).

To insert multiple lines of code put ``` before and after.

**Comment by lele-blue** [comment]
Can you launch the games through the itch client / are they installed via the itch client?

**Comment by Kuki77** [comment]
Hi,
yes, I can install and start the via the itch client.
But: 
- I can't start them via Gog Galaxy
- In Gog Galady under "itch", only the installed games are listed (right one for test) and not all the games I have via itch.
Regards
Kuki77

**Comment by lele-blue** [comment]
@Kuki77 sorry for the late response
Listing games that aren't installed isn't currently a feature of the plugin as stated in the readme.
Launching and listing installed games however should be supported.

> In Gog Galady under "itch", only the installed games are listed

This should be the right behaviour.
Does launching the games work from Gog Galaxy?
